import Head from "next/head";
import Image from "next/image";
import { useForm } from "react-hook-form";
import { loginApi, loginData } from "../api/authApi";
import { UserContext } from "@/context/UserContext";
import { useContext, useEffect } from "react";
import { cookies, fetchSubreddits } from "@/api/subredditApi";
import { useQuery } from "react-query";
import { LoadingPage } from "@/components/LoadingSpinner";
import Link from "next/link";
import Header from "@/components/Header";

export default function Home() {
  const [user, setUser] = useContext(UserContext);
  useEffect(() => {
    console.log(user);
  }, [user]);

  const {
    data: subredditData,
    isLoading: subredditsLoading,
    error: subredditsError,
  } = useQuery("allSubreddits", () => fetchSubreddits());

  if (subredditsLoading) {
    return <LoadingPage />;
  }

  if (subredditsError) {
    return <div>error</div>;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="max-w-[1280px] mx-auto">
        <h2 className="text-center font-semibold text-2xl my-5 text-slate-50">
          Subreddits
        </h2>
        <div className="flex justify-center space-x-6">
          <div className=" w-[600px] grid grid-cols-2 gap-2">
            {subredditData?.map((sub) => {
              return (
                <Link
                  className="rounded bg-slate-100 px-2 py-1 text-center border-2 border-slate-400 hover:border-orange-500"
                  key={sub.id}
                  href={`/r/${sub.name}`}
                >
                  <div>Visit {sub.name}</div>
                  <div>{sub.description}</div>
                </Link>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
}
